baseurl = "/"
languageCode = "en-us"
title = "benjamintoll.com"
theme = "hugo-lithium-theme"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Links"
    url = "/links/"

[params]
    description = "benjamintoll.com"

    [params.logo]
    url = "pete.jpeg"
    width = 50
    height = 50
    alt = "I am Pete"

