BaseURL = "/"
languageCode = "en-us"
title = "benjamintoll.com"
theme = "hugo-lithium-theme"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Articles"
    url = "/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
[[menu.main]]
    name = "Links"
    url = "/links/"
[[menu.main]]
    name = "Support"
    url = "/support/"

[params]
    description = "benjamintoll.com"
    minimal = false
    favicon = "dog.ico"

    [params.logo]
    url = "pete.jpeg"
    width = 50
    height = 50
    alt = "I am Pete"

